"""Add resume detection and feedback history fields

Revision ID: 8de919615377
Revises: 
Create Date: 2025-12-25 23:32:19.243331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de919615377'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_resume_valid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('detection_details', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('feedback_history', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_submissions', schema=None) as batch_op:
        batch_op.drop_column('feedback_history')
        batch_op.drop_column('detection_details')
        batch_op.drop_column('is_resume_valid')

    # ### end Alembic commands ###
