"""add job_type work_mode company_name location experience_level to job_postings

Revision ID: ab8c5454b538
Revises: 8de919615377
Create Date: 2026-01-05 10:41:16.033103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab8c5454b538'
down_revision = '8de919615377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('work_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('experience_level', sa.String(length=50), nullable=True))

    with op.batch_alter_table('resume_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('inferred_skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('explicit_skills', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_submissions', schema=None) as batch_op:
        batch_op.drop_column('explicit_skills')
        batch_op.drop_column('inferred_skills')
        batch_op.drop_column('status')

    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_column('experience_level')
        batch_op.drop_column('location')
        batch_op.drop_column('company_name')
        batch_op.drop_column('work_mode')
        batch_op.drop_column('job_type')

    # ### end Alembic commands ###
